import React from 'react';
import { FileText, Download, Eye, RotateCw, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { downloadReportPdf } from '../../utils/pdfGenerator';

export function ReportListTable({ reports, onRegenerate, onDelete }) {
    if (!reports || reports.length === 0) {
        return (
            <div className="text-center py-12 bg-slate-50 rounded-xl border border-dashed border-slate-300">
                <FileText className="w-10 h-10 text-slate-300 mx-auto mb-3" />
                <h3 className="text-slate-900 font-medium">No reports generated yet</h3>
                <p className="text-slate-500 text-sm mt-1">Generate your first report from a Task Detail page.</p>
            </div>
        );
    }

    return (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <table className="w-full text-left text-sm">
                <thead>
                    <tr className="bg-slate-50 border-b border-slate-200">
                        <th className="px-6 py-4 font-semibold text-slate-900">Report Name</th>
                        <th className="px-6 py-4 font-semibold text-slate-900">Task Source</th>
                        <th className="px-6 py-4 font-semibold text-slate-900">Generated By</th>
                        <th className="px-6 py-4 font-semibold text-slate-900">Date</th>
                        <th className="px-6 py-4 font-semibold text-slate-900 text-right">Actions</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                    {reports.map((report) => (
                        <tr key={report.id} className="hover:bg-slate-50/50 transition-colors">
                            <td className="px-6 py-4">
                                <div className="flex items-center gap-3">
                                    <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                                        <FileText className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="font-medium text-slate-900">{report.name}</p>
                                        <p className="text-xs text-slate-500">{report.size}</p>
                                    </div>
                                </div>
                            </td>
                            <td className="px-6 py-4 text-slate-600">Task #{report.taskId}</td>
                            <td className="px-6 py-4 text-slate-600">{report.generatedBy}</td>
                            <td className="px-6 py-4 text-slate-600">
                                {new Date(report.date).toLocaleDateString()}
                            </td>
                            <td className="px-6 py-4 text-right">
                                <div className="flex items-center justify-end gap-2">
                                    <Link
                                        to={`/reports/${report.id}`}
                                        className="p-2 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                                        title="View Preview"
                                    >
                                        <Eye className="w-4 h-4" />
                                    </Link>
                                    <button
                                        onClick={() => downloadReportPdf(report.taskId, `${report.name}.pdf`)}
                                        className="p-2 text-slate-500 hover:text-green-600 hover:bg-green-50 rounded-lg transition-colors"
                                        title="Download PDF"
                                    >
                                        <Download className="w-4 h-4" />
                                    </button>
                                    <button
                                        onClick={() => onRegenerate(report)}
                                        className="p-2 text-slate-500 hover:text-amber-600 hover:bg-amber-50 rounded-lg transition-colors"
                                        title="Regenerate"
                                    >
                                        <RotateCw className="w-4 h-4" />
                                    </button>
                                    <button
                                        onClick={() => {
                                            if (window.confirm('Delete this report?')) {
                                                // We need to pass a callback props for delete from parent, 
                                                // but for now let's assume parent handles regenerate, we might need a generic onAction or specific onDelete.
                                                // Actually ReportListTable only has onRegenerate props. 
                                                // I will add onDelete prop in next step. For now just adding UI.
                                                onDelete && onDelete(report);
                                            }
                                        }}
                                        className="p-2 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                        title="Delete"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}
